### PR TITLE
added progress bar display with Term::ProgressBar.

### PR DESCRIPTION
**Pull request by ryochin**
I guess it's slighty useful everyone can see ETA while long downloading period.

### CODE REVIEW

**Comment by oalders** [comment]
@xaicron this no longer introduces any new dependencies.  Did you have any further thoughts on it?

**Comment by oalders** [comment]
@ryochin do you have a moment to rebase this?  I think we can merge and deploy it.

**Comment by manwar** [comment]
> @ryochin do you have a moment to rebase this? I think we can merge and deploy it.

Here is pull request with rebase:
https://github.com/xaicron/p5-www-youtube-download/pull/50

**Comment by oalders** [comment]
This has been rebased and now lives in d741addc3416658.  Thanks @ryochin!

**Pull request closed without merging**
